name: Deploy to Production (Kamal)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy
        required: false
        default: main
  push:
    branches: [ main ]

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Kamal
        run: |
          gem install kamal --no-document

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        if: env.REGISTRY_SERVER != ''
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_SERVER }}
          username: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          password: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
        env:
          REGISTRY_SERVER: ${{ secrets.KAMAL_REGISTRY_SERVER }}

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >> ~/.ssh/config <<EOF
          Host *
            StrictHostKeyChecking no
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KAMAL_SSH_PRIVATE_KEY }}

      - name: Export secrets/env
        run: |
          echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> $GITHUB_ENV
          echo "KAMAL_REGISTRY_PASSWORD=${{ secrets.KAMAL_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
          if [ -n "${{ secrets.KAMAL_REGISTRY_SERVER }}" ]; then echo "KAMAL_REGISTRY_SERVER=${{ secrets.KAMAL_REGISTRY_SERVER }}" >> $GITHUB_ENV; fi
          if [ -n "${{ secrets.KAMAL_PROXY_HOST }}" ]; then echo "KAMAL_PROXY_HOST=${{ secrets.KAMAL_PROXY_HOST }}" >> $GITHUB_ENV; fi

      - name: Show Kamal version
        run: kamal --version

      - name: Build & Push image
        run: |
          kamal build --push

      - name: Deploy
        run: |
          kamal deploy


