name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      service:
        description: Cloud Run service name
        required: false
        default: jeonghwa-app
      region:
        description: GCP region (e.g. asia-northeast3)
        required: false
        default: asia-northeast3
      base_url:
        description: Public base URL for the app
        required: false
        default: https://xn--2i4b17iihloh20d.kr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth (gcr.io)
        run: gcloud auth configure-docker gcr.io -q

      - name: Build and push image (gcr.io)
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ inputs.region }}
          SERVICE: ${{ inputs.service }}
        run: |
          IMAGE=gcr.io/${PROJECT_ID}/${SERVICE}:$(git rev-parse --short HEAD)
          docker build -t ${IMAGE} .
          docker push ${IMAGE}

      - name: Deploy to Cloud Run (gcr.io)
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ inputs.region }}
          SERVICE: ${{ inputs.service }}
          BASE_URL: ${{ inputs.base_url }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          IMAGE=gcr.io/${PROJECT_ID}/${SERVICE}:$(git rev-parse --short HEAD)
          gcloud run deploy ${SERVICE} \
            --image=${IMAGE} \
            --project=${PROJECT_ID} \
            --region=${REGION} \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=BASE_URL=${BASE_URL},RAILS_MASTER_KEY=${RAILS_MASTER_KEY}



